### ISSUE TITLE
Gnome keyring does not get unlocked

### ISSUE THREAD

**Issue by mgiritli** [hhfeuer/Gentoo-Gnome-3.28-X#8]
I'm having a problem with the gnome keyring that it does not get unloced automatically after login so it asks for the password to get it unlocked. Any solutions about this?

**Comment by hhfeuer** [comment]
When does the passwort prompt show up, directly after login? Logon and keyring password match?

**Comment by mgiritli** [comment]
It comes up right after login. Yes, they match, i.e., I can unlock the keyring with the loin password. I didn't do any password change anyway, this was an upgrade from 3.24 where everything was working. I'm thinking about flushing the entire keyring...

**Comment by hhfeuer** [comment]
Right after login, can you please post the output of
journalctl -b0 --no-pager |grep pam
(run as root)

**Comment by hhfeuer** [comment]
You shouldn't delete your keyring and passwords, try if downgrading either gnome-keyring or gdm fixes the issue.

**Comment by hhfeuer** [comment]
Ok, found out what's happening with it. This whole gnome-keyring is so absurdly broken, it has always only worked by coincidence and the fact that the password was always present in memory. Since that was a security flaw, and has been changed with 3.28, so the whole thing broke down.
I've now introduced a workaround by pre-starting the daemon so it's working again.
Really fixing this requires the gnome-keyring people to fix their code. 
Please sync and check.

**Comment by aspann** [comment]
I've tested it on two diffrent machines and can confirm the workaround is 'fixing' that keyring autologin issue.

unfixed until: https://github.com/hhfeuer/Gentoo-Gnome-3.28-X/commit/bdfcce90824c6f98dec6167ad88cdd2008c0f95c Push tracker-miners, bump tracker, change gnome-photos, gnome-documen…
fixed by: https://github.com/hhfeuer/Gentoo-Gnome-3.28-X/commit/43ca4e0dfb3e7925644ae18c5a0c3af51ce857be Fix gnome-keyring with a workaround

I think this can be closed.

**Comment by hhfeuer** [comment]
Thanks for testing. Closing.
